int32 OriginID
int32 TargetID
---
RelationshipMessage theRelationship	
	
	# RelationshipMessage contains:
		# VectorMessage desired_relationship
		# VectorMessage actual_relationship
		# int32 cell_id
		
		# VectorMessage contains:
			# float64 x
			# float64 y